import os
import sys
import boto3
import requests
import json

def main():
    # Get command line arguments
    diff_content = sys.argv[1]
    pr_number = sys.argv[2]
    repository = sys.argv[3]

    # 1. Initialize AWS Bedrock client
    bedrock = boto3.client(
        service_name='bedrock-runtime',
        region_name='us-east-1'  # Change to your preferred region
    )

    # 2. Construct the prompt with correct Claude format
    prompt_message = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1000,
        "temperature": 0.7,
        "messages": [
            {
                "role": "user",
                "content": f"Please review this code diff and provide constructive feedback:\n\n{diff_content}"
            }
        ]
    }

    try:
        # 3. Call AWS Bedrock API
        # 3. Call AWS Bedrock API
        response = bedrock.invoke_model(
            modelId='anthropic.claude-v2',
            body=json.dumps(prompt_message)
        )

        # 4. Parse the response
        response_body = json.loads(response['body'].read().decode('utf-8'))
        print("Response from Bedrock:")
        print(json.dumps(response_body, indent=2))
        

        # Extract the content from the response
        if 'content' in response_body:
            review_texts = [item['text'] for item in response_body['content'] 
                          if item['type'] == 'text']
            review_comment = '\n'.join(review_texts)
        else:
            review_comment = response_body.get('completion', '')

        print("Review comment generated by Bedrock:")
        print(review_comment)
        print("Posting review comment to GitHub PR...")

        # 5. Post comment to GitHub PR
        github_token = os.environ.get('GITHUB_TOKEN')
        if not github_token:
            raise ValueError("GITHUB_TOKEN environment variable is not set")

        api_url = f"https://api.github.com/repos/{repository}/issues/{pr_number}/comments"
        
        headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
        
        data = {
            "body": review_comment
        }

        response = requests.post(api_url, headers=headers, json=data)
        response.raise_for_status()

        print("Code review comment posted successfully!")

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()